#!/usr/bin/env node
winston = require('winston');
logging = new winston.Logger({
  transports: [ new winston.transports.Console({
    level: 'debug'
  })]
});


webConf = require('./conf/web_server.conf').config;
webConf.logging = logging;
logConf = require('./conf/log_server.conf').config;
logConf.logging = logging;
server = require('../../Log.io');
logServer = new server.LogServer(logConf);
webServer = new server.WebServer(logServer, webConf);
webServer.run();

conf = require('./conf/harvester.conf').config;
conf.logging = logging;
harvester = require('../../Log.io');
harvester = new harvester.LogHarvester(conf);
harvester.run();
